#!/bin/sh
set -e
set -o pipefail

USAGE="$0 [-v] [--paste] [<name>]"

usage() {
  echo "$USAGE"
  echo "publish stdin (or pasteboard) to ipfs"
  exit 0
}

die() {
  echo >&2 "error: $@"
  exit 1
}

log() {
  if [ $verbose ]; then
    printf >&2 "$@"
  fi
}

# todo: make this cross-platform
case `uname` in
Darwin)
  clicopy="pbcopy"
  clipaste="pbpaste"
  ;;
Linux)
  clicopy="xsel -i"
  clipaste="xsel -o"
  ;;
*) ;;
esac

# get user options
while [ $# -gt 0 ]; do
  # get options
  arg="$1"
  shift

  case "$arg" in
  -h|--help) usage ;;
  -v|--verbose) verbose=1 ;;
  --paste) paste=1 ;;
  --*)
    die "unrecognised option: '$arg'\n$USAGE" ;;
  *)
    if [ "$name" = "" ]; then
      name="$arg"
    else
      die "too many arguments\n$USAGE"
    fi
    ;;
  esac
done


if [ "$name" = "" ]; then
  name=paste
fi

if [ $paste ]; then
  [[ $clipaste ]] || die "clipboard paste unkown for "`uname`
  log "paste to ipfs..."
  fhash=$($clipaste | ipfs add -q)
else
  log "stdin to ipfs..."
  fhash=$(cat | ipfs add -q)
fi
log " $fhash\n"


log "constructing dir..."
dir=$(ipfs object new unixfs-dir)
dir=$(ipfs object patch "$dir" add-link "$name" "$fhash" )
pin=$(ipfs pin add -r "$dir")
log " $dir\n"

log "copying url to clipboard..."
out="http://gateway.ipfs.io/ipfs/$dir/$name"
echo "$out" | $clicopy
log " copied\n"
echo "$out"

log "preloading on the gateways..."
(curl "$out" 2>/dev/null >/dev/null && log " ok\n") || (true && log " n/a\n")
